### ISSUE TITLE
I cannot install creoleparser on  python3.5

### ISSUE THREAD

**Issue by zhangsanfu** [pallets/flask-website#71]
```
> pip install creoleparser
Collecting creoleparser
  Downloading https://files.pythonhosted.org/packages/2a/0c/f442415eae7f0bb077fed28f6f8b1ddb07b32f216b2268dca9c267655f0d/Creoleparser-0.7.4.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-za4c4apq\creoleparser\setup.py", line 6
        print 'setuptools not installed, using distutils.core'
                                                             ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-za4c4apq\creoleparser\
```

**Comment by ThiefMaster** [comment]
same as #70
